const puppeteer = require('puppeteer-core');
const path = require('path');
const URL = 'file:///' + path.resolve(__dirname, '../index.html').split(path.sep).join('/');
(async () => {
  const br = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--autoplay-policy=no-user-gesture-required', '--no-sandbox', '--window-size=1280,720'] });
  const pg = await br.newPage(); await pg.setViewport({ width: 1280, height: 720 });
  const logs = [], reqs = [];
  pg.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') logs.push(m.type() + ': ' + m.text()); });
  pg.on('pageerror', e => logs.push('pageerror: ' + e.message));
  pg.on('request', r => { if (!r.url().startsWith('file:') && !r.url().startsWith('data:')) reqs.push(r.url()); });
  await pg.goto(URL); await new Promise(r => setTimeout(r, 800));
  const shot = async n => { await pg.screenshot({ path: path.join(__dirname, 'shots', n + '.png') }); };
  const ev = f => pg.evaluate(f);
  const wait = ms => new Promise(r => setTimeout(r, ms));
  await shot('00_boot');
  await pg.mouse.click(640, 360); await wait(600); await shot('01_title');
  await ev(() => __RT.ui.Screens.godSelect()); await wait(300); await shot('02_god');
  await ev(() => { __RT.ui.Game.pendingGod = 'mercy'; __RT.ui.Screens.opening(); }); await wait(2500); await shot('03_opening1');
  await ev(() => { __RT.ui.Game.op.i = 1; __RT.ui.Game.op.typed = 0; }); await wait(2500); await shot('03_opening2');
  await ev(() => { __RT.ui.Game.op.i = 2; __RT.ui.Game.op.typed = 0; }); await wait(2000); await shot('03_opening3');
  await ev(() => { __RT.ui.Game.op.i = 4; __RT.ui.Game.op.typed = 0; }); await wait(2000); await shot('03_opening5');
  await ev(() => __RT.ui.Screens.opEnd()); await wait(500);
  await ev(() => { __RT.ui.Game.speedIdx = 3; }); await wait(9000); await ev(() => { __RT.ui.Game.speedIdx = 1; }); await wait(500); await shot('04_play');
  console.log(await ev(() => JSON.stringify(__RT.state())));
  await ev(() => __RT.ui.Screens.chronicle()); await wait(300); await shot('05_chron'); await ev(() => __RT.ui.Screens.closeAll());
  await ev(() => __RT.ui.Screens.residents()); await wait(300); await shot('06_res'); await ev(() => __RT.ui.Screens.closeAll());
  await ev(() => __RT.ui.Screens.counsel()); await wait(300); await shot('07_counsel'); await ev(() => __RT.ui.Screens.closeAll());
  await ev(() => __RT.ui.Screens.souls()); await wait(300); await shot('08_souls'); await ev(() => __RT.ui.Screens.closeAll());
  await ev(() => __RT.ui.Screens.pause()); await wait(300); await shot('09_pause'); await ev(() => __RT.ui.Screens.settings()); await wait(300); await shot('10_settings'); await ev(() => __RT.ui.Screens.closeAll());
  console.log('errors:', JSON.stringify(await ev(() => __RT.errors())), 'logs:', JSON.stringify(logs), 'requests:', JSON.stringify(reqs));
  await br.close();
})().catch(e => { console.error('FAIL', e); process.exit(1); });
