const puppeteer = require('puppeteer-core');
const path = require('path');
const URL = 'file:///' + path.resolve(__dirname, '../index.html').split(path.sep).join('/');
const lang = process.argv[2] || 'ja';
(async () => {
  const br = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--autoplay-policy=no-user-gesture-required', '--no-sandbox', '--window-size=1280,720'] });
  const pg = await br.newPage(); await pg.setViewport({ width: 1280, height: 720 });
  const logs = [];
  pg.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') logs.push(m.type() + ': ' + m.text()); });
  pg.on('pageerror', e => logs.push('pageerror: ' + e.message));
  await pg.evaluateOnNewDocument(l => { try { localStorage.setItem('rinne_tenbin_v1_settings', JSON.stringify({ bgm: 0.6, se: 0.7, speed: 0, text: 3, lang: l, names: 'key', theme: 'black', autoSlow: true, advisor: true, tutDone: false })); } catch (e) { } }, lang);
  await pg.goto(URL); await new Promise(r => setTimeout(r, 600));
  const wait = ms => new Promise(r => setTimeout(r, ms));
  const shot = async n => { await pg.screenshot({ path: path.join(__dirname, 'shots', 'tut_' + lang + '_' + n + '.png') }); };
  const ev = f => pg.evaluate(f);
  const out = [];
  const ck = (n, c, x) => out.push((c ? 'PASS ' : 'FAIL ') + n + (x ? ' ' + x : ''));
  await pg.mouse.click(640, 360); await wait(400);
  await ev(() => { __RT.ui.Game.pendingGod = 'mercy'; __RT.ui.Screens.opEnd(); }); await wait(900);
  ck('tutorial started', await ev(() => !!__RT.ui.Game.tut && __RT.ui.Game.tut.on));
  await shot('01_intro');
  const humanPos = () => ev(() => { const T = __RT.ui.Game.tut; const hh = __RT.G().idx[T.hid]; const R = __RT.ui.Render; return { x: (hh.x * 16 + 8 - R.cam.x) * 2, y: (hh.y * 16 - 2 - R.cam.y) * 2 }; });
  let p = await humanPos(); await pg.mouse.click(p.x, p.y); await wait(400);
  ck('step intro done', await ev(() => __RT.ui.Game.tut.i) === 1, 'i=' + await ev(() => __RT.ui.Game.tut.i)); await shot('02_card');
  await ev(() => __RT.ui.Game.tut.next()); await wait(300); await shot('03_pick');
  const rec = await ev(() => { const T = __RT.ui.Game.tut; const pr = __RT.G().prayers.find(q => q.id === T.pid); return POWERS.findIndex(x => x.id === PRAYER_ANS[pr.kind][0]); });
  await pg.keyboard.press(String(rec + 1)); await wait(400);
  ck('power selected -> cast step', await ev(() => __RT.ui.Game.tut.i) === 3); await shot('04_cast');
  p = await humanPos(); await pg.mouse.click(p.x, p.y); await wait(400);
  if (await ev(() => __RT.ui.Game.modals.join(',')) === 'menu') { await ev(() => { const b = document.querySelector('#modal .btn'); b.click(); }); await wait(400); }
  ck('cast done -> result step', await ev(() => __RT.ui.Game.tut.i) === 4, 'i=' + await ev(() => __RT.ui.Game.tut.i)); await shot('05_result');
  await ev(() => __RT.ui.Game.tut.next()); await wait(300); await shot('06_chron_hint');
  await pg.keyboard.press('h'); await wait(500); ck('chron opened -> chron2', await ev(() => __RT.ui.Game.tut.i) === 6); await shot('07_chron_open');
  await pg.keyboard.press('Escape'); await wait(400); ck('chron closed -> counsel', await ev(() => __RT.ui.Game.tut.i) === 7);
  await pg.keyboard.press('g'); await wait(400); await pg.keyboard.press('Escape'); await wait(400); ck('counsel closed -> balance', await ev(() => __RT.ui.Game.tut.i) === 9); await shot('08_balance');
  await ev(() => __RT.ui.Game.tut.next()); await wait(200); await shot('09_speed'); await ev(() => __RT.ui.Game.tut.next()); await wait(200); await shot('10_end'); await ev(() => __RT.ui.Game.tut.next()); await wait(300);
  ck('tutorial finished', await ev(() => !__RT.ui.Game.tut)); ck('tutDone saved', await ev(() => __RT.ui.Game.settings.tutDone === true));
  // names / tooltips
  await ev(() => { __RT.ui.Game.speedIdx = 1; }); await wait(6000); await ev(() => { __RT.ui.Game.paused = true; }); await wait(200); await shot('11_names');
  await pg.mouse.move(640, 676); await wait(700); await shot('12_tip_power');
  await ev(() => __RT.ui.Screens.help()); await wait(300); await shot('13_help');
  console.log(out.join('\n')); console.log('errors:', JSON.stringify(await ev(() => __RT.errors())), 'logs:', JSON.stringify(logs));
  await br.close();
})().catch(e => { console.error('FAIL', e && e.stack ? e.stack.split(String.fromCharCode(10)).slice(0, 4).join(String.fromCharCode(10)) : e); process.exit(1); });
