const fs=require('fs');let s=fs.readFileSync('src/15_main.js','utf8');
function rep(a,b){const k=s.indexOf(a);if(k<0){console.log('MISSING '+a.slice(0,70));return;}s=s.slice(0,k)+b+s.slice(k+a.length);}
rep("function onCanvasDown(e) {\n  Snd.unlock(); if (Game.scene !== 'play' || Game.modals.length) return;\n  const p = Scale.toStage(e);\n  if (e.button === 2) { e.preventDefault(); if (Game.power) { Game.power = null; UI.refresh(true); } return; }\n",
"function onCanvasDown(e) {\n  Snd.unlock(); if (Game.scene !== 'play' || Game.modals.length) return;\n  const p = Scale.toStage(e);\n  if (e.button === 2) { e.preventDefault(); if (Game.power) { Game.power = null; UI.refresh(true); } return; }\n  if (e.button !== 0) return;\n  Game.drag = { sx: p.x, sy: p.y, cx: Render.cam.x, cy: Render.cam.y, moved: false };\n}\nfunction canvasClick(p) {\n  if (Game.scene !== 'play' || Game.modals.length) return;\n");
rep("function boot() {","function dragMove(e) {\n  const d = Game.drag; if (!d) return; if (Game.modals.length || Game.scene !== 'play') { endDrag(); return; }\n  const p = Scale.toStage(e); const dx = p.x - d.sx, dy = p.y - d.sy;\n  if (!d.moved && Math.hypot(dx, dy) <= 4) return;\n  if (!d.moved) { d.moved = true; Game.follow = 0; $('game').style.cursor = 'grabbing'; }\n  Render.cam.x = d.cx - dx / 2; Render.cam.y = d.cy - dy / 2; Render.clampCam();\n}\nfunction endDrag() { Game.drag = null; const c = $('game'); if (c) c.style.cursor = ''; }\nfunction dragUp(e) {\n  const d = Game.drag; if (!d || e.button !== 0) return; const was = d.moved; endDrag();\n  if (!was) canvasClick({ x: d.sx, y: d.sy });\n}\nfunction boot() {");
rep("  cv.addEventListener('mousedown', onCanvasDown);","  window.addEventListener('mousemove', dragMove); window.addEventListener('mouseup', dragUp); window.addEventListener('blur', endDrag);\n  cv.addEventListener('wheel', e => { if (Game.scene !== 'play' || Game.modals.length || e.ctrlKey) return; e.preventDefault(); Render.cam.x += e.deltaX / 2; Render.cam.y += e.deltaY / 2; Game.follow = 0; Render.clampCam(); }, { passive: false });\n  cv.addEventListener('mousedown', onCanvasDown);");
rep("      if (this.mouseCanvas && !moved) { const m = this.mouse;","      if (this.mouseCanvas && !moved && !this.drag) { const m = this.mouse;");
rep("    Render.clampCam(); Render.draw(stopped ? 0 : this.acc, {});","    if (this.drag && (this.modals.length || sc !== 'play')) endDrag();\n    Render.clampCam(); Render.draw(stopped ? 0 : this.acc, {});");
fs.writeFileSync('src/15_main.js',s);
