const fs = require('fs');
process.chdir(__dirname + '/src');
function rep(file, from, to) { let s = fs.readFileSync(file, 'utf8'); if (!s.includes(from)) { console.log('MISSING in', file, ':', from.slice(0, 80)); return; } s = s.replace(from, () => to); fs.writeFileSync(file, s); }
const f = '13_ui.js';
rep(f, "    E.tutWin = h('div', { class: 'win glass', style: 'left:8px;top:216px;width:214px;padding:4px 8px' });\n    E.selWin = h('div', { class: 'win glass', style: 'left:8px;top:392px;width:292px;display:none;padding:5px 8px' });", "    E.goalWin = UI.buildGoal();\n    E.selWin = h('div', { class: 'win glass', style: 'left:8px;top:350px;width:300px;display:none;padding:5px 8px' });");
rep(f, "h('h3', null, t('favored')), E.favList = h('div'));", "h('h3', null, t('favored')), E.favList = h('div'));\n    E.feedWin = UI.buildFeed();");
rep(f, "left:1018px;top:466px;width:254px;padding:4px 8px' }, h('h3', null, t('favored'))", "left:1018px;top:568px;width:254px;height:64px;overflow:hidden;padding:2px 8px' }, h('h3', { style: 'margin:0 0 2px;font-size:13px' }, t('favored'))");
rep(f, "    E.log = h('div', { style: 'position:absolute;left:300px;top:100px;width:700px;height:80px;pointer-events:none' });\n", "");
rep(f, "[E.faithWin, E.balWin, E.timeWin, E.bossWin, E.miniWin, E.tutWin, E.selWin, E.prayWin, E.favWin, E.log, E.powWin,", "[E.faithWin, E.balWin, E.timeWin, E.bossWin, E.miniWin, E.goalWin, E.selWin, E.prayWin, E.feedWin, E.favWin, E.powWin,");
rep(f, "    this.lastPray = ''; this.lastFav = ''; this.resRefs = null; this.tutSig = '';\n    this.refresh(true);", "    this.lastPray = ''; this.lastFav = ''; this.resRefs = null; this.tutSig = '';\n    this.attachTips(); this.renderFeed();\n    this.refresh(true);");
rep(f, "        h('span', { class: 'btn', style: 'padding:0 7px;font-size:13px', title: t('help'), onclick: () => Screens.help() }, '?'),", "        E.namesBtn = h('span', { class: 'btn', style: 'padding:0 7px;font-size:13px', onclick: () => Game.cycleNames() }, t('names_btn')),\n        h('span', { class: 'btn', style: 'padding:0 7px;font-size:13px', onclick: () => Screens.help() }, '?'),");
rep(f, "h('span', { class: 'btn', style: 'padding:0 7px;font-size:13px', title: t('menu'), onclick: () => Screens.pause() }, '☰')));", "h('span', { class: 'btn', style: 'padding:0 7px;font-size:13px', onclick: () => Screens.pause() }, '☰')));");
rep(f, "const prs = openPrayers().sort((a, b) => b.urg - a.urg).slice(0, 5);", "const allP = openPrayers().sort((a, b) => b.urg - a.urg); const prs = allP.slice(0, 4); this.prayMore = allP.length - prs.length;");
rep(f, "const sig = prs.map(p => p.id + ':' + (Game.selId === p.hid ? 1 : 0)).join(',') + LANG;", "const sig = prs.map(p => p.id + ':' + (Game.selId === p.hid ? 1 : 0)).join(',') + LANG + this.prayMore;");
rep(f, "        const card = h('div', { class: 'card u' + (p.urg > 0.75 ? 2 : p.urg > 0.5 ? 1 : 0) + (Game.selId === p.hid ? ' sel' : ''), onclick: () => Screens.prayerClick(p.id) },", "        const rc = recommendFor(p); const card = h('div', { class: 'card u' + (p.urg > 0.75 ? 2 : p.urg > 0.5 ? 1 : 0) + (Game.selId === p.hid ? ' sel' : ''), style: 'padding:2px 6px', onclick: () => Screens.prayerClick(p.id), onmouseenter: () => { Game.flashId = p.hid; }, onmouseleave: () => { if (Game.flashId === p.hid) Game.flashId = 0; } },");
rep(f, "          h('div', { class: 'sm', style: 'line-height:1.25;height:30px;overflow:hidden' }, pr(S['pray_' + p.kind][p.v % S['pray_' + p.kind].length])),", "          h('div', { class: 'sm', style: 'line-height:1.22;height:32px;overflow:hidden;font-size:13px' }, pr(S['pray_' + p.kind][p.v % S['pray_' + p.kind].length])),\n          h('div', { style: 'font-size:12px;color:#9affb0;margin-top:1px' }, t('rec_label') + '：' + POWER_BY_ID[rc.pid].n[li()] + ' ' + rc.mark + ' ' + Math.round(rc.p * 100) + '%'),");
rep(f, "        p._bar.style.width = '100%'; card._p = p; E.prayList.appendChild(card);", "        p._bar.style.width = '100%'; card._p = p; Tip.attach(card, () => [t('pk_' + p.kind), t('tipk_' + p.kind), t('tip_pray_d'), t('tip_urg'), '›' + t('rec_label') + '：' + POWER_BY_ID[rc.pid].n[li()] + '（' + t('tip_succ') + ' ' + Math.round(rc.p * 100) + '%）']); E.prayList.appendChild(card);");
rep(f, "    this.refreshPrayers(); this.refreshFav(); this.refreshTut(); this.refreshRes();", "    this.refreshPrayers(); this.refreshFav(); this.refreshGoal(); this.refreshRes();");
rep(f, "    this.bannerT = performance.now() + 2600;", "    this.bannerT = performance.now() + (Game.tut && Game.tut.on ? 60000 : 5200);");
rep(f, "if (sub) b.appendChild(h('div', { style: 'font-size:15px;margin-top:3px', class: 'sm' }, sub));", "if (sub) (Array.isArray(sub) ? sub : [sub]).forEach((l, i) => b.appendChild(h('div', { style: 'font-size:15px;margin-top:3px;line-height:1.4;' + (i === 0 ? 'color:#fff' : ''), class: 'sm' }, l)));");
rep(f, "left:340px;top:170px;width:600px;text-align:center;display:none;padding:10px 14px;font-size:20px", "left:330px;top:120px;width:620px;text-align:center;display:none;padding:10px 14px;font-size:20px;z-index:20");
rep(f, "  const nmz = res.name ? res.name[li()] : '';\n  let sub = (nmz ? nmz + ' — ' : '') + POWER_BY_ID[pid].n[li()] + '（' + t('succ') + ' ' + Math.round(res.p * 100) + '%）';\n  if (res.biasKind && res.outcome !== 'fail') sub += '\\n' + (nmz ? nmz + ' ' : '') + t('bias_' + res.biasKind);\n  if (res.side) sub += '\\n' + t('side_' + res.side);\n  UI.banner(t('out_' + res.outcome), sub.split('\\n').join(' / '), res.outcome);", "  const nmz = res.name ? res.name[li()] : '';\n  const head = (nmz ? nmz + ' ← ' : '') + POWER_BY_ID[pid].n[li()] + '（' + t('succ') + ' ' + Math.round(res.p * 100) + '%）';\n  UI.banner(t('out_' + res.outcome) + ' ' + t('out_sub_' + res.outcome), [head].concat(castReason(res)), res.outcome);\n  if (Game.tut && Game.tut.on) Game.tut.afterCast(res);");
// timeStopped includes tutorial pause
rep(f, "get timeStopped() { return this.paused || this.modals.length > 0 || this.scene !== 'play'; },", "get timeStopped() { return this.paused || this.modals.length > 0 || this.scene !== 'play' || !!(this.tut && this.tut.on && this.tut.freeze); },");
// default settings
rep(f, "settings: { bgm: 0.6, se: 0.7, speed: 1, text: 2, lang: 'ja' }", "settings: { bgm: 0.6, se: 0.7, speed: 0, text: 2, lang: 'ja', names: 'key', theme: 'black', autoSlow: true, advisor: true, tutDone: false }");
// time window names button & tips attach function
rep(f, "  show(v) { const root = $('ui'); root.style.display = v ? 'block' : 'none'; },", "  show(v) { const root = $('ui'); root.style.display = v ? 'block' : 'none'; },\n  attachTips() {\n    const E = this.el;\n    Tip.attach(E.faithWin, () => [t('tip_faith'), t('tip_faith_d')]); Tip.attach(E.balWin, () => [t('tip_bal'), t('tip_bal_d')]); Tip.attach(E.dateTxt, () => [t('tip_date'), t('tip_date_d')]);\n    E.spBtns.forEach(b => Tip.attach(b, () => [t('tip_speed'), t('tip_speed_d')])); Tip.attach(E.namesBtn, () => [t('tip_names'), t('tip_names_d'), '›' + t('names_' + (Game.settings.names || 'key'))]);\n    Tip.attach(E.miniWin, () => [t('tip_mini'), t('tip_mini_d')]); Tip.attach(E.favWin, () => [t('tip_fav'), t('tip_fav_d')]);\n    Tip.attach(E.eyeBtn, () => [t('tip_eye'), t('tip_eye_d')]); Tip.attach(E.counselBtn, () => [t('tip_counsel'), t('tip_counsel_d')]); Tip.attach(E.chronBtn, () => [t('tip_chron'), t('tip_chron_d')]);\n    E.powBtns.forEach((b, i) => { const p = POWERS[i]; Tip.attach(b, () => { const hh = Game.selId ? hById(Game.selId) : null; const L = [p.n[li()] + '　' + t('tip_cost') + ' ' + powerCost(p.id), t('tipp_' + p.id), '›' + t('tip_good') + '：' + t('tipg_' + p.id), '›' + t('tip_risk') + '：' + t('tipr_' + p.id)]; L.push(hh && hh.alive && p.id !== 'force' ? t('tip_succ') + ' ' + Math.round(successProb(p.id, hh) * 100) + '%（' + hh.name[li()] + '）' : t('tip_pick')); return L; }); });\n  },");
rep(f, "      E.eyeBtn = h('div', { class: 'btn', style: 'flex:1;text-align:center;white-space:normal;padding:2px', onclick: () => { Game.power = Game.power === 'eye' ? null : 'eye'; UI.refresh(true); } }, h('div', null, h('span', { class: 'kbd' }, 'X'), t('eye'))),\n      h('div', { class: 'btn', style: 'flex:1;text-align:center;white-space:normal;padding:2px', onclick: () => Screens.counsel() }, h('div', null, h('span', { class: 'kbd' }, 'G'), t('counsel'))),\n      h('div', { class: 'btn', style: 'flex:1.3;text-align:center;white-space:normal;padding:2px', onclick: () => Screens.chronicle() }, h('div', null, h('span', { class: 'kbd' }, 'H'), t('chronicle'))));", "      E.eyeBtn = h('div', { class: 'btn', style: 'flex:1;text-align:center;white-space:normal;padding:2px', onclick: () => { Game.power = Game.power === 'eye' ? null : 'eye'; UI.refresh(true); } }, h('div', null, h('span', { class: 'kbd' }, 'X'), t('eye'))),\n      E.counselBtn = h('div', { class: 'btn', style: 'flex:1;text-align:center;white-space:normal;padding:2px', onclick: () => Screens.counsel() }, h('div', null, h('span', { class: 'kbd' }, 'G'), t('counsel'))),\n      E.chronBtn = h('div', { class: 'btn', style: 'flex:1.3;text-align:center;white-space:normal;padding:2px', onclick: () => Screens.chronicle() }, h('div', null, h('span', { class: 'kbd' }, 'H'), t('chronicle'))));");
Object.assign(globalThis, {});
const s = fs.readFileSync(f, 'utf8');
console.log('patched; length', s.length);
